### ISSUE TITLE
Can't get it to run a command

### ISSUE THREAD

**Issue by simonbugler** [rioj7/commandOnAllFiles#1]
I'm using: 

    "commandOnAllFiles.commands": {
        "Inline CSS": {
            "command": "Inline CSS"
          }
    }

and have tried various combinations of command and extension id - but doesn't run.

What am I doing wrong?

**Comment by rioj7** [comment]
@simonbugler
`Inline CSS` is not a VSC command, you have to find the command ID for this command with the **Keyboard Shortcuts** editor.

1. Use menu: **File** > **Preferences** > **Keyboard Shortcuts**
1. Search for `Inline`
2. Locate the `Inline CSS` command
3. From context menu: **Copy Command ID**
4. Use this as the value of the `"command"` property

**Comment by simonbugler** [comment]
Worked perfectly - thank you

**Comment by yoisel** [comment]
@rioj7 That comment of yours should be copied/pasted here: https://github.com/rioj7/commandOnAllFiles#example

**Comment by rioj7** [comment]
@yoisel see v0.3.1
