### ISSUE TITLE
Adding include list of folders as another option besides exclude list

### ISSUE THREAD

**Issue by chodorowicz** [rioj7/commandOnAllFiles#2]
Hey!
Thanks for this extension. I was looking for a way to do this kind of operation.

What do you think about adding also `includeFolders` options as an additional way to define what folders would be included. Include lists are generally safer than exclude lists. It's because you need to intentionally define for what items some actions will be performed. With exclude lists it's easy to forget about some folder since by default everything is included besides items in exclude lists.

E.g. I'd like to define `includeList: ["src"]` to be sure that only files inside `src` folder will be affected.

**Comment by rioj7** [comment]
@chodorowicz  Try v0.3.0, `includeFolders` is an array with Glob Patterns. Best to use `["/src/"]` for your example

**Comment by chodorowicz** [comment]
I've tried it out and it works flawlessy for me! Amazing! Thanks so much 🙇‍♂️ 🥳
