### ISSUE TITLE
Doesn't work with rescurse directories

### ISSUE THREAD

**Issue by ylazy** [rioj7/commandOnAllFiles#4]
The extension only works with some files, not all recurse files on my workspace, then finished.

**Comment by rioj7** [comment]
@ylazy without more details about your workspace (local, remote, multi root, tunnel, ....), your configuration of the command, the files in the workspace (full directory tree, at least a representation).

You supply no information for me to recreate the issue and find the cause.

2k+ people use it without problems, so you must have some special setup.

**Comment by ylazy** [comment]
@rioj7 sorry for missing the details. I edited the content but forgot to save.
I'm using a local workspace.
Please view this video for more details:
https://drive.google.com/file/d/1c4MRxxVa5JWLYXzpplks9UFSlOVWpAx2/view?usp=sharing

Thanks!

**Comment by rioj7** [comment]
@ylazy  Using the video I can't exactly recreate your setup.

Those `.as` files are they ActionScript from Adobe?
Do you still use Flash/Actionscript (Flash is not supported for years by browsers, too many bugs/security loopholes),

Do I need to use an extension to get Import Organize for these files?

What is the exact file path of the Workspace you have open?
What are the (relative or full) file paths of a few files it does modify?
What are the (relative or full) file paths of a few files it does **NOT** modify?
What is the value of your setting: `commandOnAllFiles.excludeFolders`
What is this YLAZYSDK? Can I find it on the internet? Are these files part of the Workspace?
What is the `VSCODE/src` path?

Can you copy/paste the part of the settings file you use.

Can you show an example content of the `.as` files (I don't use those files) so I can test if the organize command works.

Why do you define a key binding for the command `commandOnAllFiles.applyOnWorkspace`?
You can find it in the Command Palette, search for **Apply 1 or more commands to all files in the Workspace**
(I will add a group label to the command and adjust the README.)

**Comment by ylazy** [comment]
@rioj7 Thank you for your quick response,

I'm using ActionScript to work with Adobe Air, not Flash. The dead thing is Flash (a browser plugin), not ActionScript ;) . You can use ActionScript to develop desktop/mobile apps using Adobe Air -  now it's [Adobe Air SDK from Harman](https://airsdk.harman.com/), or transpile to Javascript using Apache Royale, and more... In this case, I'm using AS to develop a windows app.

Organize Imports is a system command, so you won't need any extension to use it. YlazySDK is my under-development framework. VSCODE is my ActionScript Project to build the YlazySDK framework.

`You can find it in the Command Palette, search for Apply 1 or more commands to all files in the Workspace`
I think it may be better to call the command "command on all files in the workspace (recurse)". I didn't find the command via "command on" keyword so I have to define a key for it.

After a day of struggling with this error, I finally address this issue. The problem is that the command "Organize Imports" require the editor is **focusing**, but whenever your extension opens a file, the editor is not get focused. So the command only affects opening editors.

Could you add an extension setting like "focus on the editor" to set the focus to the editor whenever a file is opened, before running commands?

Thank you!

**Comment by rioj7** [comment]
@ylazy  When I give VSC the command to open a file it loads it in an active editor. If the file is already part of a tab-group it brings the tab to the front and makes that editor the current editor.

Please answer my **What** questions so I can recreate the issue.

The fact that a particular tab from the YlazySDK is not closed after the command means they are not visited by the command.

Is YlazySDK part of the Workspace?

If your assumption: `the editor is not get focused` is true a lot more users would have trouble with the extension.

Looking at the video do you use an extension to get those rows of file tabs per group?
Do you use the setting: `workbench.editor.wrapTabs`, what if you set it to `false` (default value)

If you look at the key binding of Organize Imports the `when` clause suggests that the language file for this languageID sets the `supportedCodeAction`. So most likely I need an extension that does the Organize Imports for that particular languageID.

In the key bind GUI you can see the text that is shown in the Command Palette.
If you search the Command Palette for `apply` you get a few hits.
In the next update the command text is: `Command On All Files: Apply 1 or more commands to all files in the Workspace`
If you then search for `command on` it will be one of very few.

**Comment by rioj7** [comment]
@ylazy  if you still have problems, supply enough information so I can recreate the problem/setup
