### ISSUE TITLE
`editor.action.organizeImports` not executed

### ISSUE THREAD

**Issue by sKopheK** [rioj7/commandOnAllFiles#9]
hi, files are correctly opened, but the command is not executed. tried a different one (example with Hello append) and it works without issues
```
  "commandOnAllFiles.commands": {
    "organizeImports": {
      "commandID": "editor.action.organizeImports",
    },
  },
  "commandOnAllFiles.includeFileExtensions": [
    ".tsx",
    ".ts"
  ],
  "commandOnAllFiles.excludeFolders": [
    "node_modules",
    "out",
    ".vscode-test",
    "media",
    ".git",
    ".next",
    ".husky"
  ],
```

**Comment by rioj7** [comment]
@sKopheK  If this is the setting you use it will not open any file. You are missing the `includeFileExtensions` or the `includeFiles` property in the `organizeImports` object.

If you use the `commandOnAllFiles.includeFileExtensions` or `commandOnAllFiles.includeFiles` you should mention that in the issue. And show there content (with dummy values for any file paths)

**Comment by sKopheK** [comment]
sorry, my bad, i do have it in global settings for the extension - updated the code; files get open (and closed shortly after if had not been open before), but they do never get updated

**Comment by rioj7** [comment]
@sKopheK  I could recreate the problem. It took quite some debugging to find the cause of the issue. The command executed was `undefined`. If you use v0.5.1 and look at the `settings.json` file you see the reason: **typo**

This should work

```
"command": "editor.action.organizeImports",
```
